//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 10:15:18 PM CEST 
//


package com.github.freeacs.ws.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unittypes" type="{http://xml.ws.freeacs.github.com/}unittypeList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unittypes"
})
@XmlRootElement(name = "GetUnittypesResponse")
public class GetUnittypesResponse {

    @XmlElementRef(name = "unittypes", namespace = "http://xml.ws.freeacs.github.com/", type = JAXBElement.class, required = false)
    protected JAXBElement<UnittypeList> unittypes;

    /**
     * Gets the value of the unittypes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link UnittypeList }{@code >}
     *     
     */
    public JAXBElement<UnittypeList> getUnittypes() {
        return unittypes;
    }

    /**
     * Sets the value of the unittypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link UnittypeList }{@code >}
     *     
     */
    public void setUnittypes(JAXBElement<UnittypeList> value) {
        this.unittypes = value;
    }

}
