//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 10:15:18 PM CEST 
//


package com.github.freeacs.ws.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.freeacs.ws.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LoginPassword_QNAME = new QName("http://xml.ws.freeacs.github.com/", "password");
    private final static QName _GetUnitIdsResponseUnits_QNAME = new QName("http://xml.ws.freeacs.github.com/", "units");
    private final static QName _UnitUnitId_QNAME = new QName("http://xml.ws.freeacs.github.com/", "unitId");
    private final static QName _UnitParameters_QNAME = new QName("http://xml.ws.freeacs.github.com/", "parameters");
    private final static QName _UnitSerialNumber_QNAME = new QName("http://xml.ws.freeacs.github.com/", "serialNumber");
    private final static QName _UnitUnittype_QNAME = new QName("http://xml.ws.freeacs.github.com/", "unittype");
    private final static QName _UnitProfile_QNAME = new QName("http://xml.ws.freeacs.github.com/", "profile");
    private final static QName _GetUnittypesResponseUnittypes_QNAME = new QName("http://xml.ws.freeacs.github.com/", "unittypes");
    private final static QName _ParameterFlags_QNAME = new QName("http://xml.ws.freeacs.github.com/", "flags");
    private final static QName _ParameterValue_QNAME = new QName("http://xml.ws.freeacs.github.com/", "value");
    private final static QName _GetProfilesResponseProfiles_QNAME = new QName("http://xml.ws.freeacs.github.com/", "profiles");
    private final static QName _UnittypeDescription_QNAME = new QName("http://xml.ws.freeacs.github.com/", "description");
    private final static QName _UnittypeMatcherId_QNAME = new QName("http://xml.ws.freeacs.github.com/", "matcherId");
    private final static QName _UnittypeProtocol_QNAME = new QName("http://xml.ws.freeacs.github.com/", "protocol");
    private final static QName _UnittypeVendor_QNAME = new QName("http://xml.ws.freeacs.github.com/", "vendor");
    private final static QName _GetUnittypesRequestUnittypeName_QNAME = new QName("http://xml.ws.freeacs.github.com/", "unittypeName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.freeacs.ws.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddOrChangeProfileResponse }
     * 
     */
    public AddOrChangeProfileResponse createAddOrChangeProfileResponse() {
        return new AddOrChangeProfileResponse();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link GetUnitsResponse }
     * 
     */
    public GetUnitsResponse createGetUnitsResponse() {
        return new GetUnitsResponse();
    }

    /**
     * Create an instance of {@link UnitList }
     * 
     */
    public UnitList createUnitList() {
        return new UnitList();
    }

    /**
     * Create an instance of {@link DeleteProfileRequest }
     * 
     */
    public DeleteProfileRequest createDeleteProfileRequest() {
        return new DeleteProfileRequest();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link Unittype }
     * 
     */
    public Unittype createUnittype() {
        return new Unittype();
    }

    /**
     * Create an instance of {@link DeleteProfileResponse }
     * 
     */
    public DeleteProfileResponse createDeleteProfileResponse() {
        return new DeleteProfileResponse();
    }

    /**
     * Create an instance of {@link AddOrChangeUnittypeRequest }
     * 
     */
    public AddOrChangeUnittypeRequest createAddOrChangeUnittypeRequest() {
        return new AddOrChangeUnittypeRequest();
    }

    /**
     * Create an instance of {@link GetUnittypesRequest }
     * 
     */
    public GetUnittypesRequest createGetUnittypesRequest() {
        return new GetUnittypesRequest();
    }

    /**
     * Create an instance of {@link GetUnitIdsRequest }
     * 
     */
    public GetUnitIdsRequest createGetUnitIdsRequest() {
        return new GetUnitIdsRequest();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link AddOrChangeUnittypeResponse }
     * 
     */
    public AddOrChangeUnittypeResponse createAddOrChangeUnittypeResponse() {
        return new AddOrChangeUnittypeResponse();
    }

    /**
     * Create an instance of {@link DeleteUnitRequest }
     * 
     */
    public DeleteUnitRequest createDeleteUnitRequest() {
        return new DeleteUnitRequest();
    }

    /**
     * Create an instance of {@link GetProfilesResponse }
     * 
     */
    public GetProfilesResponse createGetProfilesResponse() {
        return new GetProfilesResponse();
    }

    /**
     * Create an instance of {@link ProfileList }
     * 
     */
    public ProfileList createProfileList() {
        return new ProfileList();
    }

    /**
     * Create an instance of {@link GetUnitIdsResponse }
     * 
     */
    public GetUnitIdsResponse createGetUnitIdsResponse() {
        return new GetUnitIdsResponse();
    }

    /**
     * Create an instance of {@link UnitIdList }
     * 
     */
    public UnitIdList createUnitIdList() {
        return new UnitIdList();
    }

    /**
     * Create an instance of {@link DeleteUnitResponse }
     * 
     */
    public DeleteUnitResponse createDeleteUnitResponse() {
        return new DeleteUnitResponse();
    }

    /**
     * Create an instance of {@link GetUnittypesResponse }
     * 
     */
    public GetUnittypesResponse createGetUnittypesResponse() {
        return new GetUnittypesResponse();
    }

    /**
     * Create an instance of {@link UnittypeList }
     * 
     */
    public UnittypeList createUnittypeList() {
        return new UnittypeList();
    }

    /**
     * Create an instance of {@link GetProfilesRequest }
     * 
     */
    public GetProfilesRequest createGetProfilesRequest() {
        return new GetProfilesRequest();
    }

    /**
     * Create an instance of {@link DeleteUnittypeResponse }
     * 
     */
    public DeleteUnittypeResponse createDeleteUnittypeResponse() {
        return new DeleteUnittypeResponse();
    }

    /**
     * Create an instance of {@link AddOrChangeProfileRequest }
     * 
     */
    public AddOrChangeProfileRequest createAddOrChangeProfileRequest() {
        return new AddOrChangeProfileRequest();
    }

    /**
     * Create an instance of {@link AddOrChangeUnitRequest }
     * 
     */
    public AddOrChangeUnitRequest createAddOrChangeUnitRequest() {
        return new AddOrChangeUnitRequest();
    }

    /**
     * Create an instance of {@link GetUnitsRequest }
     * 
     */
    public GetUnitsRequest createGetUnitsRequest() {
        return new GetUnitsRequest();
    }

    /**
     * Create an instance of {@link AddOrChangeUnitResponse }
     * 
     */
    public AddOrChangeUnitResponse createAddOrChangeUnitResponse() {
        return new AddOrChangeUnitResponse();
    }

    /**
     * Create an instance of {@link DeleteUnittypeRequest }
     * 
     */
    public DeleteUnittypeRequest createDeleteUnittypeRequest() {
        return new DeleteUnittypeRequest();
    }

    /**
     * Create an instance of {@link ArrayOfUnit }
     * 
     */
    public ArrayOfUnit createArrayOfUnit() {
        return new ArrayOfUnit();
    }

    /**
     * Create an instance of {@link ArrayOfUnitId }
     * 
     */
    public ArrayOfUnitId createArrayOfUnitId() {
        return new ArrayOfUnitId();
    }

    /**
     * Create an instance of {@link ArrayOfUnittype }
     * 
     */
    public ArrayOfUnittype createArrayOfUnittype() {
        return new ArrayOfUnittype();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ParameterList }
     * 
     */
    public ParameterList createParameterList() {
        return new ParameterList();
    }

    /**
     * Create an instance of {@link ArrayOfProfile }
     * 
     */
    public ArrayOfProfile createArrayOfProfile() {
        return new ArrayOfProfile();
    }

    /**
     * Create an instance of {@link ArrayOfParameter }
     * 
     */
    public ArrayOfParameter createArrayOfParameter() {
        return new ArrayOfParameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "password", scope = Login.class)
    public JAXBElement<String> createLoginPassword(String value) {
        return new JAXBElement<String>(_LoginPassword_QNAME, String.class, Login.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitIdList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "units", scope = GetUnitIdsResponse.class)
    public JAXBElement<UnitIdList> createGetUnitIdsResponseUnits(UnitIdList value) {
        return new JAXBElement<UnitIdList>(_GetUnitIdsResponseUnits_QNAME, UnitIdList.class, GetUnitIdsResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "unitId", scope = Unit.class)
    public JAXBElement<String> createUnitUnitId(String value) {
        return new JAXBElement<String>(_UnitUnitId_QNAME, String.class, Unit.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "parameters", scope = Unit.class)
    public JAXBElement<ParameterList> createUnitParameters(ParameterList value) {
        return new JAXBElement<ParameterList>(_UnitParameters_QNAME, ParameterList.class, Unit.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "serialNumber", scope = Unit.class)
    public JAXBElement<String> createUnitSerialNumber(String value) {
        return new JAXBElement<String>(_UnitSerialNumber_QNAME, String.class, Unit.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Unittype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "unittype", scope = Unit.class)
    public JAXBElement<Unittype> createUnitUnittype(Unittype value) {
        return new JAXBElement<Unittype>(_UnitUnittype_QNAME, Unittype.class, Unit.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Profile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "profile", scope = Unit.class)
    public JAXBElement<Profile> createUnitProfile(Profile value) {
        return new JAXBElement<Profile>(_UnitProfile_QNAME, Profile.class, Unit.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "parameters", scope = Profile.class)
    public JAXBElement<ParameterList> createProfileParameters(ParameterList value) {
        return new JAXBElement<ParameterList>(_UnitParameters_QNAME, ParameterList.class, Profile.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnittypeList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "unittypes", scope = GetUnittypesResponse.class)
    public JAXBElement<UnittypeList> createGetUnittypesResponseUnittypes(UnittypeList value) {
        return new JAXBElement<UnittypeList>(_GetUnittypesResponseUnittypes_QNAME, UnittypeList.class, GetUnittypesResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "flags", scope = Parameter.class)
    public JAXBElement<String> createParameterFlags(String value) {
        return new JAXBElement<String>(_ParameterFlags_QNAME, String.class, Parameter.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "value", scope = Parameter.class)
    public JAXBElement<String> createParameterValue(String value) {
        return new JAXBElement<String>(_ParameterValue_QNAME, String.class, Parameter.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProfileList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "profiles", scope = GetProfilesResponse.class)
    public JAXBElement<ProfileList> createGetProfilesResponseProfiles(ProfileList value) {
        return new JAXBElement<ProfileList>(_GetProfilesResponseProfiles_QNAME, ProfileList.class, GetProfilesResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "description", scope = Unittype.class)
    public JAXBElement<String> createUnittypeDescription(String value) {
        return new JAXBElement<String>(_UnittypeDescription_QNAME, String.class, Unittype.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "parameters", scope = Unittype.class)
    public JAXBElement<ParameterList> createUnittypeParameters(ParameterList value) {
        return new JAXBElement<ParameterList>(_UnitParameters_QNAME, ParameterList.class, Unittype.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "matcherId", scope = Unittype.class)
    public JAXBElement<String> createUnittypeMatcherId(String value) {
        return new JAXBElement<String>(_UnittypeMatcherId_QNAME, String.class, Unittype.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "protocol", scope = Unittype.class)
    public JAXBElement<String> createUnittypeProtocol(String value) {
        return new JAXBElement<String>(_UnittypeProtocol_QNAME, String.class, Unittype.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "vendor", scope = Unittype.class)
    public JAXBElement<String> createUnittypeVendor(String value) {
        return new JAXBElement<String>(_UnittypeVendor_QNAME, String.class, Unittype.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "unittypeName", scope = GetUnittypesRequest.class)
    public JAXBElement<String> createGetUnittypesRequestUnittypeName(String value) {
        return new JAXBElement<String>(_GetUnittypesRequestUnittypeName_QNAME, String.class, GetUnittypesRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "units", scope = GetUnitsResponse.class)
    public JAXBElement<UnitList> createGetUnitsResponseUnits(UnitList value) {
        return new JAXBElement<UnitList>(_GetUnitIdsResponseUnits_QNAME, UnitList.class, GetUnitsResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Profile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.ws.freeacs.github.com/", name = "profile", scope = GetProfilesRequest.class)
    public JAXBElement<Profile> createGetProfilesRequestProfile(Profile value) {
        return new JAXBElement<Profile>(_UnitProfile_QNAME, Profile.class, GetProfilesRequest.class, value);
    }

}
