//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 10:15:18 PM CEST 
//


package com.github.freeacs.ws.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unittypeList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="unittypeList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unittypeArray" type="{http://xml.ws.freeacs.github.com/}ArrayOfUnittype"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unittypeList", propOrder = {
    "unittypeArray"
})
public class UnittypeList {

    @XmlElement(required = true)
    protected ArrayOfUnittype unittypeArray;

    /**
     * Gets the value of the unittypeArray property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfUnittype }
     *     
     */
    public ArrayOfUnittype getUnittypeArray() {
        return unittypeArray;
    }

    /**
     * Sets the value of the unittypeArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfUnittype }
     *     
     */
    public void setUnittypeArray(ArrayOfUnittype value) {
        this.unittypeArray = value;
    }

}
