//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 10:15:18 PM CEST 
//


package com.github.freeacs.ws.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unitIdList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="unitIdList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitIdArray" type="{http://xml.ws.freeacs.github.com/}ArrayOfUnitId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unitIdList", propOrder = {
    "unitIdArray"
})
public class UnitIdList {

    @XmlElement(required = true)
    protected ArrayOfUnitId unitIdArray;

    /**
     * Gets the value of the unitIdArray property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfUnitId }
     *     
     */
    public ArrayOfUnitId getUnitIdArray() {
        return unitIdArray;
    }

    /**
     * Sets the value of the unitIdArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfUnitId }
     *     
     */
    public void setUnitIdArray(ArrayOfUnitId value) {
        this.unitIdArray = value;
    }

}
