//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.22 at 10:15:18 PM CEST 
//


package com.github.freeacs.ws.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unitList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="unitList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitArray" type="{http://xml.ws.freeacs.github.com/}ArrayOfUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unitList", propOrder = {
    "unitArray"
})
public class UnitList {

    @XmlElement(required = true)
    protected ArrayOfUnit unitArray;

    /**
     * Gets the value of the unitArray property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfUnit }
     *     
     */
    public ArrayOfUnit getUnitArray() {
        return unitArray;
    }

    /**
     * Sets the value of the unitArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfUnit }
     *     
     */
    public void setUnitArray(ArrayOfUnit value) {
        this.unitArray = value;
    }

}
