version: '2.2'
services:
  nginx:
    image: freeacs/nginx
    mem_limit: 1000000000
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    links:
      - web
      - webservice
      - tr069
      - stun
      - syslog
      - core
  web:
    image: freeacs/freeacs-web
    restart: always
    mem_limit: 2048000000
    depends_on:
    - db
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE
      - MAIN_DATASOURCE_JDBCURL
      - MAIN_DATASOURCE_USERNAME
      - MAIN_DATASOURCE_PASSWORD
      - MONITOR_LOCATION
      - SYSLOG_SERVER_HOST
      - SERVER_PORT
      - TZ
    volumes:
      - web_logs:/opt/docker/logs
#     - ./conf/web/application-config.properties:/opt/docker/config/application-config.properties
#     - ./conf/web/logback.xml:/opt/docker/config/logback.xml
  monitor:
    image: freeacs/freeacs-monitor
    restart: always
    mem_limit: 2048000000
    depends_on:
    - db
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE
      - MONITOR_URL_CORE
      - MONITOR_URL_SYSLOG
      - MONITOR_URL_TR069
      - MONITOR_URL_WEB
      - MONITOR_URL_WEBSERVICE
      - MONITOR_URL_STUN
      - SYSLOG_SERVER_HOST
      - SERVER_PORT
      - TZ
    volumes:
      - monitor_logs:/opt/docker/logs
#     - ./conf/monitor/application-config.properties:/opt/docker/config/application-config.properties
#     - ./conf/monitor/logback.xml:/opt/docker/config/logback.xml
  tr069:
    image: freeacs/freeacs-tr069
    restart: always
    mem_limit: 2048000000
    depends_on:
    - db
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE
      - MAIN_DATASOURCE_JDBCURL
      - MAIN_DATASOURCE_USERNAME
      - MAIN_DATASOURCE_PASSWORD
      - SYSLOG_SERVER_HOST
      - SERVER_PORT
      - TZ
    volumes:
      - tr069_logs:/opt/docker/logs
#     - ./conf/tr069/application-config.properties:/opt/docker/config/application-config.properties
#     - ./conf/tr069/logback.xml:/opt/docker/config/logback.xml
  syslog:
    image: freeacs/freeacs-syslog
    restart: always
    mem_limit: 2048000000
    depends_on:
    - db
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE
      - MAIN_DATASOURCE_JDBCURL
      - MAIN_DATASOURCE_USERNAME
      - MAIN_DATASOURCE_PASSWORD
      - SYSLOG_SERVER_HOST
      - SERVER_PORT
      - TZ
    volumes:
      - syslog_logs:/opt/docker/logs
#     - ./conf/syslog/application-config.properties:/opt/docker/config/application-config.properties
#     - ./conf/syslog/logback.xml:/opt/docker/config/logback.xml
  core:
    image: freeacs/freeacs-core
    restart: always
    mem_limit: 2048000000
    depends_on:
    - db
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE
      - MAIN_DATASOURCE_JDBCURL
      - MAIN_DATASOURCE_USERNAME
      - MAIN_DATASOURCE_PASSWORD
      - SYSLOG_SERVER_HOST
      - SERVER_PORT
      - TZ
    volumes:
      - core_logs:/opt/docker/logs
#     - ./conf/core/application-config.properties:/opt/docker/config/application-config.properties
#     - ./conf/core/logback.xml:/opt/docker/config/logback.xml
  stun:
    image: freeacs/freeacs-stun
    restart: always
    mem_limit: 2048000000
    depends_on:
    - db
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE
      - MAIN_DATASOURCE_JDBCURL
      - MAIN_DATASOURCE_USERNAME
      - MAIN_DATASOURCE_PASSWORD
      - SYSLOG_SERVER_HOST
      - SERVER_PORT
      - TZ
    volumes:
      - stun_logs:/opt/docker/logs
#     - ./conf/stun/application-config.properties:/opt/docker/config/application-config.properties
#     - ./conf/stun/logback.xml:/opt/docker/config/logback.xml
  webservice:
    image: freeacs/freeacs-webservice
    restart: always
    mem_limit: 2048000000
    depends_on:
    - db
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE
      - MAIN_DATASOURCE_JDBCURL
      - MAIN_DATASOURCE_USERNAME
      - MAIN_DATASOURCE_PASSWORD
      - SYSLOG_SERVER_HOST
      - SERVER_PORT
      - TZ
    volumes:
      - webservice_logs:/opt/docker/logs
#     - ./conf/webservice/application-config.properties:/opt/docker/config/application-config.properties
#     - ./conf/webservice/logback.xml:/opt/docker/config/logback.xml
  db:
    image: freeacs/mysql
    command: --max_allowed_packet=32M
    restart: always
    mem_limit: 1000000000
    environment:
      - TZ
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mynetwork:
        aliases:
          - db.main
          - db.syslog

volumes:
  mysql-data:
  core_logs:
  web_logs:
  webservice_logs:
  syslog_logs:
  stun_logs:
  tr069_logs:
  monitor_logs:

networks:
  mynetwork:
    driver: bridge