version: '2.2'
services:
  nginx:
    image: freeacs/nginx
    mem_limit: 1000000000
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    links:
      - web
      - webservice
      - tr069
      - stun
      - syslog
      - core
  web:
    image: freeacs/freeacs-web
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - MONITOR_LOCATION=http://monitor:8080
      - SERVER_PORT=8080
    volumes:
      - web_logs:/opt/docker/logs
      - ./conf/web:/opt/docker/config:ro
  monitor:
    image: freeacs/freeacs-monitor
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MONITOR_URL_CORE=http://core:8080/core/ok
      - MONITOR_URL_SYSLOG=http://syslog:8080/syslog/ok
      - MONITOR_URL_TR069=http://tr069:8080/tr069/ok
      - MONITOR_URL_WEB=http://web:8080/web/ok
      - MONITOR_URL_WEBSERVICE=http://webservice:8080/webservice/ok
      - MONITOR_URL_STUN=http://stun:8080/stun/ok
      - SERVER_PORT=8080
    volumes:
      - web_logs:/opt/docker/logs
      - ./conf/web:/opt/docker/config:ro
  tr069:
    image: freeacs/freeacs-tr069
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - tr069_logs:/opt/docker/logs
      - ./conf/tr069:/opt/docker/config:ro
  syslog:
    image: freeacs/freeacs-syslog
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - syslog_logs:/opt/docker/logs
      - ./conf/syslog:/opt/docker/config:ro
  core:
    image: freeacs/freeacs-core
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - core_logs:/opt/docker/logs
      - ./conf/core:/opt/docker/config:ro
  stun:
    image: freeacs/freeacs-stun
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - stun_logs:/opt/docker/logs
      - ./conf/stun:/opt/docker/config:ro
  webservice:
    image: freeacs/freeacs-webservice
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs?autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&requireSSL=false
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - webservice_logs:/opt/docker/logs
      - ./conf/webservice:/opt/docker/config:ro
  db:
    image: freeacs/mysql
    command: --max_allowed_packet=32M
    restart: always
    mem_limit: 1000000000
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mynetwork:
        aliases:
          - db.main
          - db.syslog

volumes:
  mysql-data:
  core_logs:
  web_logs:
  webservice_logs:
  syslog_logs:
  stun_logs:
  tr069_logs:

networks:
  mynetwork:
    driver: bridge