version: '2.2'
services:
  nginx:
    image: freeacs/nginx
    mem_limit: 1000000000
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    links:
      - web
      - webservice
      - tr069
      - stun
      - syslog
      - core
  web:
    image: freeacs/web
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - web_logs:/opt/docker/logs
      - ./conf/web:/opt/docker/conf:ro
  tr069:
    image: freeacs/tr069
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - tr069_logs:/opt/docker/logs
      - ./conf/tr069:/opt/docker/conf:ro
  syslog:
    image: freeacs/syslog
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - syslog_logs:/opt/docker/logs
      - ./conf/syslog:/opt/docker/conf:ro
  core:
    image: freeacs/core
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - core_logs:/opt/docker/logs
      - ./conf/core:/opt/docker/conf:ro
  stun:
    image: freeacs/stun
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - stun_logs:/opt/docker/logs
      - ./conf/stun:/opt/docker/conf:ro
  webservice:
    image: freeacs/webservice
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_PROFILES_ACTIVE=config
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - SERVER_PORT=8080
    volumes:
      - webservice_logs:/opt/docker/logs
      - ./conf/webservice:/opt/docker/conf:ro
  db:
    image: freeacs/mysql
    restart: always
    mem_limit: 1000000000
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      mynetwork:
        aliases:
          - db.main
          - db.syslog

volumes:
  mysql-data:
  core_logs:
  web_logs:
  webservice_logs:
  syslog_logs:
  stun_logs:
  tr069_logs:

networks:
  mynetwork:
    driver: bridge