version: '2.2'
services:
  nginx:
    image: nginx:latest
    mem_limit: 1000000000
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork
  web:
    image: freeacs/web
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_CONFIG_LOCATION=/opt/docker/data/application.properties
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - LOG_PATH=/opt/docker/data/logs
    volumes:
      - ./data/web:/opt/docker/data
  tr069:
    image: freeacs/tr069
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_CONFIG_LOCATION=/opt/docker/data/application.properties
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - LOG_PATH=/opt/docker/data/logs
    volumes:
      - ./data/tr069:/opt/docker/data
  syslog:
    image: freeacs/syslog
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_CONFIG_LOCATION=/opt/docker/data/application.properties
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - LOG_PATH=/opt/docker/data/logs
    volumes:
      - ./data/syslog:/opt/docker/data
  core:
    image: freeacs/core
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_CONFIG_LOCATION=/opt/docker/data/application.properties
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - LOG_PATH=/opt/docker/data/logs
    volumes:
      - ./data/core:/opt/docker/data
  stun:
    image: freeacs/stun
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_CONFIG_LOCATION=/opt/docker/data/application.properties
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - LOG_PATH=/opt/docker/data/logs
    volumes:
      - ./data/stun:/opt/docker/data
  webservice:
    image: freeacs/webservice
    restart: always
    mem_limit: 2048000000
    networks:
      - mynetwork
    environment:
      - SPRING_CONFIG_LOCATION=/opt/docker/data/application.properties
      - MAIN_DATASOURCE_JDBCURL=jdbc:mysql://db.main:3306/acs
      - MAIN_DATASOURCE_USERNAME=acs
      - MAIN_DATASOURCE_PASSWORD=acs
      - SYSLOG_DATASOURCE_JDBCURL=jdbc:mysql://db.syslog:3306/acs
      - SYSLOG_DATASOURCE_USERNAME=acs
      - SYSLOG_DATASOURCE_PASSWORD=acs
      - LOG_PATH=/opt/docker/data/logs
    volumes:
      - ./data/webservice:/opt/docker/data
  db:
    build: mysql
    restart: always
    mem_limit: 1000000000
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      mynetwork:
        aliases:
          - db.main
          - db.syslog
networks:
  mynetwork:
    driver: bridge