version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - web
      - tr069
    networks:
      - mynetwork
  web:
    image: web
    restart: always
    networks:
      - mynetwork
  tr069:
    image: tr069
    restart: always
    networks:
      - mynetwork
  syslog:
    image: syslog
    restart: always
    networks:
      - mynetwork
  core:
    image: core
    restart: always
    networks:
      - mynetwork
  stun:
    image: stun
    restart: always
    networks:
      - mynetwork
  webservice:
    image: webservice
    restart: always
    networks:
      - mynetwork
  db:
    build: mysql
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      mynetwork:
        aliases:
          - db.main
          - db.syslog
volumes:
  mysql-db:

networks:
  mynetwork:
    driver: bridge