###########################
#                         #
#     COMMON MAKEFILE     #
#                         #
###########################

VERSION_NUMBER := latest
DOWNLOAD_ARTIFACTS := zip
MYSQL_ACS_PASSWORD :=
MYSQL_ROOT_PASSWORD :=

cleanup:
	@echo " -> cleaning up";
	@rm -rf files.txt .tmp *.rpm *.zip *.deb *.pdf *.sql;
	@echo " -> done cleaning";

download-release: | cleanup
	@echo " -> downloading FreeACS resources"
	@echo "${DOWNLOAD_ARTIFACTS}"
	@curl -s https://api.github.com/repos/freeacs/freeacs/releases/${VERSION_NUMBER} | \
		jq -r ".assets[] | select(.name | test(\"${DOWNLOAD_ARTIFACTS}\")) | .browser_download_url" \
		> files.txt;
	@awk '{print $0;}' files.txt | xargs -L1 wget;
	@unzip "*.zip";
	@echo " -> all necessary FreeACS resources are available.";

load-tables:
	$(eval tablepresent = `mysql -uacs -p$acsdbpw acs -e "SHOW TABLES LIKE 'unit_type'" 2> /dev/null  | wc -l`)
ifeq ($(tablepresent),2)
	@echo "WARNING! An important FreeACS table is found in the database,"
	@echo "indicating that the database tables have already been loaded. "
	@echo "If you decide to load all table definitions, you will delete "
	@echo "ALL FreeACS data in the database, and start over."
	@read -p "Load all table defintions (and overwriting all data)? (y/n): " yn
ifeq ($(yn), y)
	@echo "Loads all FreeACS table defintions into MySQL"
	@mysql -uacs -p'${MYSQL_ACS_PASSWORD}' acs < install.sql
endif
endif

setup-user:
	@echo "Setu up acs user"
	@mysql -uroot -p'${MYSQL_ROOT_PASSWORD}' -e "CREATE DATABASE acs"
	@mysql -uroot -p'${MYSQL_ROOT_PASSWORD}' acs -e "CREATE USER 'acs'@'localhost' IDENTIFIED BY '${MYSQL_ACS_PASSWORD}'"
	@mysql -uroot -p'${MYSQL_ROOT_PASSWORD}' acs -e "GRANT ALL ON acs.* TO 'acs' IDENTIFIED BY '${MYSQL_ACS_PASSWORD}'"
	@mysql -uroot -p'${MYSQL_ROOT_PASSWORD}' acs -e "GRANT ALL ON acs.* TO 'acs'@'localhost' IDENTIFIED BY '${MYSQL_ACS_PASSWORD}'"
