###########################
#                         #
#     UBUNTU MAKEFEILE    #
#                         #
###########################

MYSQL_ROOT_PASSWORD :=
MYSQL_ACS_PASSWORD :=

install_mysql:
	@echo ' -> Do ubuntu mysql stuff'
