version: '3'
services:
    data-api:
      build: .
      links:
        - mysql
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      ports:
        - "9000:9000"
    mysql:
      image: freeacs/mysql
